version: '3.8'
services:
  app:
    container_name: shiningstar
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongo-example
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: 
    #   MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - 27017:27017
  #   volumes:
  #     - mongodata:/data/db
  # volumes:
  #   mongodata:
  #     driver: local
